# Site that is hosting these files
site = "https://myrient.erista.me"

# The path to the directory these files are located in
path_directory = "/files/No-Intro/Nintendo - Game Boy/"

# Directory where files will be downloaded:
directory = "gb"

# List of files to download:
files = [
  "Pokemon - Blue Version (USA, Europe) (SGB Enhanced).zip",
  "Pokemon - Red Version (USA, Europe) (SGB Enhanced).zip",
  "Pokemon - Yellow Version - Special Pikachu Edition (USA, Europe) (CGB+SGB Enhanced).zip"
]
