site = "https://myrient.erista.me"

[bios_platforms.atarilynx]
path = "/files/No-Intro/Atari - Atari Lynx (LYX)/"
directory = "bios/lynx"
files = [
    "[BIOS] Atari Lynx (World).zip"
]

[bios_platforms.gba]
path = "/files/No-Intro/Nintendo - Game Boy Advance/"
directory = "bios/gba"
files = [
    "[BIOS] Nintendo Game Boy Advance Boot ROM (World).zip"
]

[bios_platforms.nds]
path = "/files/No-Intro/Nintendo - Nintendo DS (Decrypted)/"
directory = "bios/nds"
files = [
    "[BIOS] Nintendo DS ARM7 Boot ROM (World).zip",
    "[BIOS] Nintendo DS ARM9 Boot ROM (World).zip",
    "[BIOS] Nintendo DS Firmware (World) (En,Ja,Fr,De,Es,It) (2005-12-07).zip"
]

[bios_platforms.psx]
path = "/files/Redump/Sony - PlayStation - BIOS Images (DoM Version)/"
directory = "bios/psx"
files = [
    "psone-45a.zip",
    "psone-45e.zip",
    "psone-43j.zip"
]

[bios_platforms.ps2]
path = "/files/Redump/Sony - PlayStation 2 - BIOS Images (DoM Version)/"
directory = "bios/ps2"
files = [
    "ps2-0230a-20080220-175343.zip",
    "ps2-0230e-20080220-175343.zip",
    "ps2-0230j-20080220-175343.zip"
]