# Myrient Collection Configuration

# Platform configurations
[roms]

[roms.gb]
url = "https://myrient.erista.me/files/No-Intro/Nintendo%20-%20Game%20Boy/"
urllist = "urls/gb.txt"
directory = "roms/gb"
skip_filtering = true
extract = false

[roms.gbc]
url = "https://myrient.erista.me/files/No-Intro/Nintendo%20-%20Game%20Boy%20Color/"
urllist = "urls/gbc.txt"
directory = "roms/gbc"
skip_filtering = true
extract = false

[roms.gba]
url = "https://myrient.erista.me/files/No-Intro/Nintendo%20-%20Game%20Boy%20Advance/"
urllist = "urls/gba.txt"
directory = "roms/gba"
skip_filtering = true
extract = false

# Platform configurations
[bios]

[bios.ps2]
url = "https://myrient.erista.me/files/Redump/Sony%20-%20PlayStation%202%20-%20BIOS%20Images%20%28DoM%20Version%29/"
urllist = "urls/ps2bios.txt"
directory = "bios/ps2"
skip_filtering = true
extract = true
