subdomain = "No-Intro/Nintendo%20-%20Game%20Boy%20Advance/"
directory = "gba/"
files = [
  "Pokemon%20-%20Emerald%20Version%20%28USA%2C%20Europe%29.zip",
  "Super%20Mario%20Advance%204%20-%20Super%20Mario%20Bros.%203%20%28USA%2C%20Australia%29%20%28Rev%201%29.zip",
  "Legend%20of%20Zelda%2C%20The%20-%20The%20Minish%20Cap%20%28USA%29.zip"
]
