# Site that is hosting these files
site = "https://myrient.erista.me"

# The path to the directory these files are located in
path_directory = "/files/No-Intro/Nintendo - Game Boy Advance/"

# Directory where files will be downloaded:
directory = "gba"

# List of files to download:
files = [
  "Pokemon - Emerald Version (USA, Europe).zip",
  "Pokemon - FireRed Version (USA, Europe) (Rev 1).zip",
  "Pokemon - LeafGreen Version (USA, Europe) (Rev 1).zip",
  "Pokemon Mystery Dungeon - Red Rescue Team (USA, Australia).zip",
  "Pokemon Pinball - Ruby &amp; Sapphire (USA).zip",
  "Pokemon - Ruby Version (USA, Europe) (Rev 2).zip",
  "Pokemon - Sapphire Version (USA, Europe) (Rev 2).zip"
]
