#site = "https://myrient.erista.me"
#path_directory = "/files/No-Intro/Nintendo - Game Boy/"
#directory = "gb/"
#files = [
#  "Game1.zip",
#  "Game2.zip"
#]

# Site that is hosting these files
site = "https://myrient.erista.me"

# The path to the directory these files are located in
path_directory = ""

# Directory where files will be downloaded:
directory = ""

# List of files to download:
files = []